"""Add alert_active

Revision ID: 4a4a308c1168
Revises: d11c83a3bb47
Create Date: 2023-05-06 23:31:13.578245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4a308c1168'
down_revision = 'd11c83a3bb47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('alert_active', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box', 'alert_active')
    # ### end Alembic commands ###
