"""boxes table

Revision ID: 68db6b7618b4
Revises: 1b0374094723
Create Date: 2022-12-01 19:26:25.868611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68db6b7618b4'
down_revision = '1b0374094723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_name'), 'box', ['name'], unique=True)
    op.create_table('indication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_box', sa.Integer(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('hum', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_box'], ['box.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indication')
    op.drop_index(op.f('ix_box_name'), table_name='box')
    op.drop_table('box')
    # ### end Alembic commands ###
