"""corrections

Revision ID: 6a07bb46cc86
Revises: b02c84ce0c07
Create Date: 2023-04-12 20:44:16.895807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a07bb46cc86'
down_revision = 'b02c84ce0c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('correct_t', sa.Float(), nullable=True))
    op.add_column('device', sa.Column('correct_h', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'correct_h')
    op.drop_column('device', 'correct_t')
    # ### end Alembic commands ###
