"""Fix alert_active

Revision ID: 6f592dc3095c
Revises: aa2eca6ac7cc
Create Date: 2023-05-06 23:25:57.483621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f592dc3095c'
down_revision = 'aa2eca6ac7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('box', 'alert_active',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('box', 'alert_active',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
