"""Added alert_active

Revision ID: 760503ddfa63
Revises: 870e32951e76
Create Date: 2023-05-06 23:18:40.636808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760503ddfa63'
down_revision = '870e32951e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('alert_active', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box', 'alert_active')
    # ### end Alembic commands ###
