"""Edited boxes on/off

Revision ID: 80ef0fd7622c
Revises: a6a5be6f902f
Create Date: 2023-05-18 18:08:26.316305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ef0fd7622c'
down_revision = 'a6a5be6f902f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('box_active', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box', 'box_active')
    # ### end Alembic commands ###
