"""Logs table edited

Revision ID: 8484481d448c
Revises: 727237081908
Create Date: 2023-04-25 16:01:22.476295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8484481d448c'
down_revision = '727237081908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('id_box', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'log', 'box', ['id_box'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_column('log', 'id_box')
    # ### end Alembic commands ###
