"""Delete alert_active

Revision ID: 870e32951e76
Revises: ce1627a833e7
Create Date: 2023-05-06 23:17:42.438492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870e32951e76'
down_revision = 'ce1627a833e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box', 'alert_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('alert_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
