"""indications table

Revision ID: 97b96224afe1
Revises: 68db6b7618b4
Create Date: 2022-12-01 19:29:43.390290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b96224afe1'
down_revision = '68db6b7618b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indication', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indication', 'time')
    # ### end Alembic commands ###
