"""Edited FCMtokens logic

Revision ID: a2b24ca61587
Revises: 4a4a308c1168
Create Date: 2023-05-12 16:07:53.916822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b24ca61587'
down_revision = '4a4a308c1168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fc_mtokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('fcm_token', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['box.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'fcmtoken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fcmtoken', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_table('fc_mtokens')
    # ### end Alembic commands ###
