"""Edited FCMtokens logic

Revision ID: a6a5be6f902f
Revises: a2b24ca61587
Create Date: 2023-05-12 16:13:28.918340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a5be6f902f'
down_revision = 'a2b24ca61587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fc_mtokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('fcm_token', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'fcmtoken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fcmtoken', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_table('fc_mtokens')
    # ### end Alembic commands ###
