"""fcm tokens

Revision ID: a920204406ad
Revises: af298cdf77ab
Create Date: 2023-03-18 19:42:58.166394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a920204406ad'
down_revision = 'af298cdf77ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fcmtoken', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'user', ['fcmtoken'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'fcmtoken')
    # ### end Alembic commands ###
