"""Added alert_active

Revision ID: aa2eca6ac7cc
Revises: 760503ddfa63
Create Date: 2023-05-06 23:20:03.369217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2eca6ac7cc'
down_revision = '760503ddfa63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('alert_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box', 'alert_active')
    # ### end Alembic commands ###
