"""Added alert_active in Box

Revision ID: ce1627a833e7
Revises: 45be53393612
Create Date: 2023-05-06 23:13:27.241157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1627a833e7'
down_revision = '45be53393612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('alert_active', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box', 'alert_active')
    # ### end Alembic commands ###
